find_library(PROTOBUFCRPC_LIBRARY
							NAMES "protobuf-c-rpc"
							PATHS "/usr" "/usr/local" "/opt" ENV PROTOBUFC_ROOTDIR
							PATH_SUFFIXES "lib")
mark_as_advanced(PROTOBUFCRPC_LIBRARY)

find_path(PROTOBUFCRPC_INCLUDE_DIR
							NAMES "protobuf-c-rpc/protobuf-c-rpc.h"
							PATHS "/usr" "/usr/local" "/opt" ENV PROTOBUFC_ROOTDIR
							PATH_SUFFIXES "include")
mark_as_advanced(PROTOBUFCRPC_INCLUDE_DIR)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ProtobufCRPC DEFAULT_MSG PROTOBUFCRPC_LIBRARY PROTOBUFCRPC_INCLUDE_DIR )

if (PROTOBUFCRPC_FOUND)
	set(PROTOBUFCRPC_LIBRARIES ${PROTOBUFC_LIBRARY})
	set(PROTOBUFCRPC_INCLUDE_DIRS ${PROTOBUFC_INCLUDE_DIR})
endif(PROTOBUFCRPC_FOUND)
